version: "3"
services:
  web:
    build: .
    restart: always
    volumes:
      - .:/www
      - /var/log/gunicorn/letmeknow/:/var/log/gunicorn/letmeknow/
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8080 letmeknow.wsgi:application --access-logfile /var/log/gunicorn/letmeknow/access.log --error-logfile /var/log/gunicorn/letmeknow/error.log"
    depends_on:
      - db
      - rabbitmq
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/var/www/letmeknow/static
      - ./media:/var/www/letmeknow/media
      - /var/log/nginx/letmeknow/:/var/log/nginx/letmeknow/
    links:
      - web
    ports:
      - "8005:8005"
    depends_on:
      - web
  db:
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  celery:
    build: .
    env_file:
      - ./.env
    command: celery -A letmeknow worker -l info
    volumes:
      - .:/wwww
    depends_on:
      - db
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1



volumes:
  postgres_data: