# Generated by Django 2.1.7 on 2019-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190321_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.CharField(default='awdawd', max_length=50),
            preserve_default=False,
        ),
    ]
