# Generated by Django 2.1.7 on 2019-03-25 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='task_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='checksum',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
