# Generated by Django 2.1.7 on 2019-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='celery_task_id',
            field=models.CharField(default='awdwd', max_length=100),
            preserve_default=False,
        ),
    ]
