# Generated by Django 2.1.7 on 2019-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
