# Generated by Django 2.1.7 on 2019-03-26 17:45

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_on',
            field=models.DateTimeField(validators=[notifications.models.in_future]),
        ),
    ]
